### ISSUE TITLE
Small issue related to spacing?

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/section#1]
I'm almost done with the first Typografier exercise but there seems to be a small issue somewhere (guessing related to spacing) that will drive me nuts. Not sure if it's important but I wanted to bring to your attention.

<img width="964" alt="Screen Shot 2021-06-29 at 2 09 49 PM" src="https://user-images.githubusercontent.com/16348315/123846978-013f4980-d8e4-11eb-8129-973d604acd4a.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
You’ve done everything correctly. So, I don’t actually know what’s going on.
